[package]
name = "vixen"
version = "0.1.0"
description = "Telegram bot for automatically banning spammers in Telegram chats"
authors = ["Mike Matiunin <plugfox@gmail.com>"]
license = "MIT"
edition = "2024"

[[bin]]
name = "server"
path = "bin/server.rs"

# cargo run --release
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.40", features = ["derive", "env"] }
