#!/usr/bin/env bun
/**
 * i18n codegen.
 *
 * Walks `i18n/messages/en/*.yaml` and emits two artefacts per namespace:
 *
 *  1. `src/shared/i18n/generated/<ns>.ts` — typed const map of `MessageDef`s
 *     consumed by application code as `t(common.save)`.
 *  2. `public/locales/<locale>/<ns>.json` — flat key→value map fetched at
 *     runtime by `shared/i18n/i18n.ts` for non-EN locales.
 *
 * Plus a `src/shared/i18n/generated/index.ts` barrel that re-exports each
 * namespace for ergonomic imports.
 *
 * Idempotent: re-running with no source change is a no-op (files are
 * overwritten with byte-identical content).
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, "..");
const SOURCE_DIR = join(ROOT, "i18n", "messages");
const TS_OUT_DIR = join(ROOT, "src", "shared", "i18n", "generated");
const JSON_OUT_DIR = join(ROOT, "public", "locales");

const LOCALES = ["en", "ru"] as const;

interface YamlEntry {
  en?: string;
  ru?: string;
}

function mkdirp(p: string): void {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function namespacesFromEn(): string[] {
  const enDir = join(SOURCE_DIR, "en");
  if (!existsSync(enDir)) {
    throw new Error(`missing en/ directory at ${enDir}`);
  }
  return readdirSync(enDir)
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => basename(f, ".yaml"))
    .sort();
}

function readNamespace(locale: string, ns: string): Record<string, string> {
  const file = join(SOURCE_DIR, locale, `${ns}.yaml`);
  if (!existsSync(file)) return {};
  const raw = readFileSync(file, "utf8");
  const parsed = (parse(raw) ?? {}) as Record<string, YamlEntry>;
  const out: Record<string, string> = {};
  for (const [key, entry] of Object.entries(parsed)) {
    const value = (entry as YamlEntry)?.[locale as keyof YamlEntry];
    if (typeof value === "string") out[key] = value;
  }
  return out;
}

function tsIdentifier(key: string): string {
  // YAML keys allow `.` and `-`; TS const keys must be valid identifiers OR
  // string literals. We emit string literals for safety.
  return JSON.stringify(key);
}

function generate(): void {
  mkdirp(TS_OUT_DIR);

  const namespaces = namespacesFromEn();

  for (const ns of namespaces) {
    const en = readNamespace("en", ns);
    // ── TypeScript const map (sourced from EN, fields stripped to MessageDef).
    const tsLines: string[] = [
      "// AUTO-GENERATED by scripts/i18n-codegen.ts — do not edit by hand.",
      `import type { MessageDef } from "../types";`,
      "",
      `export const ${ns} = {`,
    ];
    for (const [key, enValue] of Object.entries(en).sort(([a], [b]) => a.localeCompare(b))) {
      tsLines.push(
        `  ${tsIdentifier(key)}: { ns: ${JSON.stringify(ns)}, key: ${JSON.stringify(key)}, en: ${JSON.stringify(enValue)} } satisfies MessageDef,`,
      );
    }
    tsLines.push("} as const;");
    tsLines.push("");
    writeFileSync(join(TS_OUT_DIR, `${ns}.ts`), tsLines.join("\n"));

    // ── Per-locale JSON for the runtime fetcher.
    for (const loc of LOCALES) {
      const map = readNamespace(loc, ns);
      const targetDir = join(JSON_OUT_DIR, loc);
      mkdirp(targetDir);
      writeFileSync(join(targetDir, `${ns}.json`), JSON.stringify(map, null, 2));
    }
  }

  // ── Barrel index.
  const indexLines: string[] = [
    "// AUTO-GENERATED by scripts/i18n-codegen.ts — do not edit by hand.",
    "",
  ];
  for (const ns of namespaces) {
    indexLines.push(`export { ${ns} } from "./${ns}";`);
  }
  indexLines.push("");
  writeFileSync(join(TS_OUT_DIR, "index.ts"), indexLines.join("\n"));

  console.log(`i18n-codegen: wrote ${namespaces.length} namespaces`);
}

generate();
